CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 name TEXT NOT NULL,
 wallet_balance NUMERIC(14,2) NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT);
CREATE TABLE IF NOT EXISTS admin_accounts (
 id SMALLINT PRIMARY KEY CHECK(id=1),
 email TEXT NOT NULL,
 password_hash TEXT NOT NULL,
 name TEXT NOT NULL DEFAULT 'Administrator',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
 product_id INTEGER NOT NULL,
 product_name TEXT NOT NULL,
 qty INTEGER NOT NULL CHECK(qty>0),
 unit_price NUMERIC(14,2) NOT NULL,
 total_amount NUMERIC(14,2) NOT NULL,
 api_order_id TEXT,
 provider TEXT,
 provider_ref TEXT,
 status TEXT NOT NULL DEFAULT 'pending',
 idempotency_key TEXT,
 product_details TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reported_at TIMESTAMPTZ,
 report_reason TEXT,
 replacement_status TEXT,
 replacement_note TEXT,
 replaced_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS wallets (
 user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 balance NUMERIC(14,2) NOT NULL DEFAULT 0,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS fund_requests (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 amount NUMERIC(14,2) NOT NULL,
 reference TEXT UNIQUE NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS schema_migrations(version TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
